---
title: "In-Class Assignment One"
author: "Noah Gallego"
date: "2024-10-04"
output: word_document
---

# In-Class Assignment: Question One

### Import Libraries and Load Dataset
```{r}
# Import Libraries
library(tidyr)
library(dplyr)
library(ggplot2)

# Load DataSet with Path
path = "../../Data"
stocks_data = read.table(
  paste(path, "/stocks.txt", sep = ""),
  header = TRUE)

# Display First Few Rows
head(stocks_data)
```

### Deal with Invalid Data Types and Missing Values
```{r}
# Convert to Correct Dtypes & Replace with NA for non-char's
stocks_data_to_numeric = select(stocks_data, AMZN, DUK, KO) %>%
                         mutate(across(!where(is.numeric), as.numeric))
stocks_data_to_numeric$Date = stocks_data$Date

# Impute NA with Mean
stocks_data_to_numeric$AMZN[is.na(stocks_data_to_numeric$AMZN)] = median(stocks_data_to_numeric$AMZN, na.rm = TRUE)   

stocks_data_to_numeric$DUK[is.na(stocks_data_to_numeric$DUK)] = median(stocks_data_to_numeric$DUK, na.rm = TRUE)   

stocks_data_to_numeric$KO[is.na(stocks_data_to_numeric$KO)] = median(stocks_data_to_numeric$KO, na.rm = TRUE)   

# Convert Data to DateTime
stocks_data_to_numeric$Date = as.Date(stocks_data_to_numeric$Date, format = "%m/%d/%Y")

head(stocks_data_to_numeric)
```

### Exploratory Data Analysis
```{r}
# Five-Number Summary in R
summary(stocks_data_to_numeric)
stocks_filtered = stocks_data_to_numeric

# Count Number of Days for Each Company the closing price was 20% Higher than the Median Price
median_AMZN = median(stocks_filtered$AMZN)
median_DUK = median(stocks_filtered$DUK)
median_KO = median(stocks_filtered$KO)

count_AMZN = nrow(stocks_filtered[stocks_filtered$AMZN > (1.2 * median_AMZN), ])
count_DUK = nrow(stocks_filtered[stocks_filtered$DUK > (1.2 * median_DUK), ])
count_KO = nrow(stocks_filtered[stocks_filtered$KO > (1.2 * median_KO), ])

paste("The number of days AMZN closed at least 20% above", median_AMZN, "is ", count_AMZN)
paste("The number of days DUK closed at least 20% above", median_DUK, "is ", count_DUK)
paste("The number of days KO closed at least 20% above", median_KO, "is ", count_KO)
```